# Generated by Django 2.1.3 on 2018-11-22 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='分组名称')),
                ('desc', models.CharField(max_length=256, verbose_name='分组简介')),
                ('image', models.ImageField(upload_to='group', verbose_name='分组图片')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '分组',
                'verbose_name': '分组',
                'db_table': 'wl_group',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('status', models.SmallIntegerField(choices=[(0, '已加入'), (1, '被移除')], default=0, verbose_name='用户状态')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group', verbose_name='所属组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='组内用户')),
            ],
            options={
                'verbose_name_plural': '分组用户',
                'verbose_name': '分组用户',
                'db_table': 'wl_group_user',
            },
        ),
    ]
